/* Schema definition generated by prostgles-server */

export type DBGeneratedSchema = {
  employees: {
    columns: {
      department?: null | string;
      id?: number;
      name?: null | string;
      salary?: null | string;
    };
  };
  futures: {
    is_view: false;
    select: true;
    // insert: true;
    // update: true;
    // delete: true;
    columns: {
      price?: null | number;
      symbol?: null | string;
      timestamp?: null | string;
    };
  };
  symbols: {
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      pair: string;
    };
  };
  users: {
    columns: {
      id?: string;
      type: string;
    };
  };
};

/**
 * Data types as expected when selecting from the database
 * */
export type DBSchema = {
  [K in keyof DBGeneratedSchema]: Required<DBGeneratedSchema[K]["columns"]>;
};

/**
 * Data types as expected when inserting into the database (optional fields might be nullable/with defaults)
 * */
export type DBSchemaForInsert = {
  [K in keyof DBGeneratedSchema]: DBGeneratedSchema[K]["columns"];
};

export type GeneratedFunctionSchema = {
  my_new_func: (args: { hey: boolean }) => Promise<unknown>;
};
